// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUOY1S34pIvaeQFIeA5f6c8b6FGwLiIms',
    appId: '1:407938215893:web:2de211840f4e4ad8b9575c',
    messagingSenderId: '407938215893',
    projectId: 'collecta-b54a9',
    authDomain: 'collecta-b54a9.firebaseapp.com',
    storageBucket: 'collecta-b54a9.firebasestorage.app',
    measurementId: 'G-HXWQ1DDKKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNUpaUJXxMjBlhPAAsn5EFQs0xqCbP2j0',
    appId: '1:407938215893:android:ef816fb3de580308b9575c',
    messagingSenderId: '407938215893',
    projectId: 'collecta-b54a9',
    storageBucket: 'collecta-b54a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCWSRA1df6sfXbHS51IYURTS2RPa13V0',
    appId: '1:407938215893:ios:f97a0aeb5523f2aeb9575c',
    messagingSenderId: '407938215893',
    projectId: 'collecta-b54a9',
    storageBucket: 'collecta-b54a9.firebasestorage.app',
    iosBundleId: 'co.colle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUOY1S34pIvaeQFIeA5f6c8b6FGwLiIms',
    appId: '1:407938215893:web:099ca5a813815953b9575c',
    messagingSenderId: '407938215893',
    projectId: 'collecta-b54a9',
    authDomain: 'collecta-b54a9.firebaseapp.com',
    storageBucket: 'collecta-b54a9.firebasestorage.app',
    measurementId: 'G-SEJH56B64T',
  );
}
